# SPDX-FileCopyrightText: 2022-2024 trobonox <hello@trobo.dev>
#
# SPDX-License-Identifier: Apache-2.0

accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-3-Clause",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "MIT-0",
    "GPL-3.0" # this is for Kanri itself
]
