# SPDX-FileCopyrightText: Copyright (c) 2022-2026 trobonox <hello@trobo.dev>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "kanri"
SPDX-PackageSupplier = "trobonox <hello@trobo.dev>"
SPDX-PackageDownloadLocation = "https://github.com/kanriapp/kanri"
annotations = []
