# SPDX-FileCopyrightText: Copyright (c) 2022-2023 trobonox <hello@trobo.tech>
#
# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: true
contact_links:
  - name: Official Kanri Discord server
    url: https://discord.gg/AVqHrvxB9C
    about: Talk to the developer, community and request support or provide feedback.
